export const SET_SORT = 'SET_SORT'
export const SORT_SIDS = 'SORT_SIDS'

export const GET_ALBUM_COMPARISON_SUCCESS = 'GET_ALBUM_COMPARISON_SUCCESS'
export const GET_ALBUM_COMPARISON_FAIL = 'GET_ALBUM_COMPARISON_FAIL'
export const POST_COMPARISON_SUCCESS = 'POST_COMPARISON_SUCCESS'
export const POST_COMPARISON_FAIL = 'POST_COMPARISON_FAIL'

export const SET_FILTER_QUERY_SUCCESS = 'SET_FILTER_QUERY_SUCCESS'
export const FITLER_COLLECTION_SUCCESS = 'FITLER_COLLECTION_SUCCESS'

export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS'
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL'
export const RESET_FILTERS = 'RESET_FILTERS'
export const POST_ALBUM_SUCCESS = 'POST_ALBUM_SUCCESS'
export const POST_ALBUM_FAIL = 'POST_ALBUM_FAIL'
export const GET_ALBUM_CATGS_SUCCESS = 'GET_ALBUM_CATGS_SUCCESS'
export const GET_ALBUM_CATGS_FAIL = 'GET_ALBUM_CATGS_FAIL'
export const POST_ALBUM_CATG_SUCCESS = 'POST_ALBUM_CATG_SUCCESS'
export const POST_ALBUM_CATG_FAIL = 'POST_ALBUM_CATG_FAIL'
export const DELETE_ALBUM_CATG_SUCCESS = 'DELETE_ALBUM_CATG_SUCCESS'
export const DELETE_ALBUM_CATG_FAIL = 'DELETE_ALBUM_CATG_FAIL'
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS'
export const DELETE_ALBUM_FAIL = 'DELETE_ALBUM_FAIL'

export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS'
export const POST_REVIEW_FAIL = 'POST_REVIEW_FAIL'
export const POST_TRACK_REVIEW_SUCCESS = 'POST_TRACK_REVIEW_SUCCESS'
export const POST_TRACK_REVIEW_FAIL = 'POST_TRACK_REVIEW_FAIL'
export const POST_LISTEN_SUCCESS = 'POST_LISTEN_SUCCESS'
export const POST_LISTEN_FAIL = 'POST_LISTEN_FAIL'
export const SET_VIEW = 'SET_VIEW'

export const CATEGORIES = [
  'art', 'critic', 'cohesive', 'depth', 'dynamics', 'flow', 'friend', 'hold', 'longevity', 'lyrics',
  'structure', 'voice'
]
